### ISSUE TITLE
403 (Forbidden)

### ISSUE THREAD

**Issue by cyllu2** [CulturalMe/meteor-slingshot#107]
Is this package up-to-date with S3 storage? I get a 403 (Forbidden) even with full permissions set to everyone and testing on every server.

**Comment by cyllu2** [comment]
Found the solution after tearing my hair out. It had to do with IAM policies (if you login as yourself to AWS but is not the actual owner, basically). Needed to upgrade myself to full administrator and then it worked!

**Comment by gsuess** [comment]
I would not recommend using credentials for users that have full admin rights on AWS for any app really.

Slingshot only needs one permission  (`s3::putObject`) on the bucket that you are uploading to:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "statement1",
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::Account-ID:user/Dave"
            },
            "Action": ["s3:PutObject"],
            "Resource": "arn:aws:s3:::examplebucket"
        }
    ]
}
```

**Comment by zaklampert** [comment]
@gsuess I'm stuck on this one too.

I have a policy just as you've shown here but i'm still getting 403'd.

Do i need a policy on the IAM user, the bucket, or both?

**Comment by JVercout** [comment]
I had to use the action `s3:PutObjectAcl` instead of `s3:PutObject` in order to make it work, and allow the put action on bucket objects (`examplebucket/*`) instead of bucket itself (`examplebucket`)

See below to permission statement, working for me. You can find the ARN coed of the user into your security dashboard.
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "statement1",
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::your-account-id:user/your-username"
            },
            "Action": "s3:PutObjectAcl",
            "Resource": "arn:aws:s3:::examplebucket/*"
        }
    ]
}
```

**Comment by Marcelrama** [comment]
Hi @JVercout , I'm trying to validate the policies but it will not let me realize I get this error.
This policy contains the following error: Has prohibited field Home For more information about the IAM policy grammar, see AWS IAM Policies


```
{
     "Version": "2012-10-17",
     "Statement": [
         {
             "Sid": "statement1",
             "Effect": "Allow",
             "Action": "ses: SendRawEmail",
             "Resource": "*"
         },
         {
             "Sid": "statement2",
             "Effect": "Allow",
             "Principal": {
                 "AWS": "arn: aws: iam :: my-id: user /my-bucket"
             },
             "Action": [
                 "S3: PutObjectAcl",
                 "S3: PutObject"
             ],
             "Resource": "arn: aws: s3 ::: my-bucket / *"
         }
     ]
}
```

**Comment by JVercout** [comment]
Hi @Marcelrama, 

I've associated the policy directly to the bucket. (S3 > Your bucket > Properties > Permissions > Edit bucket policy)

* Are you trying to add the policy to the user directly? In this case, I'm not sure of the syntax that you should use.
* In the given statement2 you gave, I've have a different "Principal" sub-object:
```
"Principal": {"AWS": "arn:aws:iam::account-id:user/**username**"},
```
While you are using **/mybucket**.
I got the user ARN from the IAM Management Console > Tab "Users" > selecting a specific user >  "User ARN" field.

Best.

**Comment by Marcelrama** [comment]
Hey @JVercout , if thanks for the detail I was giving the permissions directly editing the user now what I did was create a permissions and that permissions are assigned to my new user, but I did not have success to achieve the connection with amazon s3 I still get


> POST https://my-bucket.s3.amazonaws.com/ 403 (Forbidden)
> Transfer @ upload.js: 197
> (Anonymous) @ upload.js: 101
> (Anonymous) @ upload.js: 132
> (Anonymous) @ dynamics_browser.js: 51
> _maybeInvokeCallback @ livedata_connection.js: 388
> ReceiveResult @ livedata_connection.js: 408
> _livedata_result @ livedata_connection.js: 1461
> OnMessage @ livedata_connection.js: 253
> (Anonymous) @ stream_client_sockjs.js: 172
> _each ._. ForEach @ underscore.js: 105
> Self.socket.onmessage @ stream_client_sockjs.js: 171
> REventTarget.dispatchEvent @ sockjs-0.3.4.js: 87
> SockJS._dispatchMessage @ sockjs-0.3.4.js: 1072
> SockJS._didMessage @ sockjs-0.3.4.js: 1130
> That.ws.onmessage @ sockjs-0.3.4.js: 1277
