### ISSUE TITLE
CORS Error - No 'Access-Control-Allow-Origin' in header

### ISSUE THREAD

**Issue by centinel3** [CulturalMe/meteor-slingshot#109]
I'm getting an error when I try and upload a file in my production environment (Modulus) into Amazon S3. File upload from my local machine works fine. Is there additional configurations needed to add an 'Access-Control-Allow-Origin' header to make this work correctly?

The error I'm getting (in Chrome):
```
XMLHttpRequest cannot load https://documents-cleaved.s3.amazonaws.com/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://cleaved-46813.onmodulus.net' is therefore not allowed access. The response had HTTP status code 403.
```
```
e.m…e.r {error: " - 0", reason: "Failed to upload file to cloud storage", details: undefined, message: "Failed to upload file to cloud storage [ - 0]", errorType: "Meteor.Error"}details: undefinederror: " - 0"errorType: "Meteor.Error"message: "Failed to upload file to cloud storage [ - 0]"reason: "Failed to upload file to cloud storage"stack: (...)get stack: () { [native code] }arguments: nullcaller: nulllength: 0name: ""prototype: StackTraceGetter__proto__: Empty() {}<function scope>set stack: () { [native code] }arguments: nullcaller: nulllength: 1name: ""prototype: StackTraceSetter__proto__: Empty() {}<function scope>__proto__: e.makeErrorType.r
```
Error I'm getting in FireFox:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://documents-cleaved.s3.amazonaws.com/. This can be fixed by moving the resource to the same domain or enabling CORS.
```

What I've tried already (server-side) that doesn't work:
```JavaScript
Meteor.startup(function () {
	WebApp.connectHandlers.use(function(req, res, next) {
	  res.setHeader("access-control-allow-origin", "*");
	  res.setHeader("access-control-allow-headers", "Origin, X-Requested-With, Content-Type, Accept");
	  return next();
	});
});
```
I also tried adding a bucket policy (which didn't seem to work):
```json
{
	"Version": "2008-10-17",
	"Statement": [
		{
			"Sid": "Stmt1433853625083",
			"Action": "s3:*",
			"Effect": "Allow",
			"Principal": "*",
			"Resource": "arn:aws:s3:::cleavedfiles/*"
		}
	]
}
```
My CORS config is:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
    <CORSRule>
        <AllowedOrigin>http://*</AllowedOrigin>
        <AllowedOrigin>https://*</AllowedOrigin>
        <AllowedMethod>PUT</AllowedMethod>
        <AllowedMethod>POST</AllowedMethod>
        <AllowedMethod>GET</AllowedMethod>
        <AllowedMethod>HEAD</AllowedMethod>
        <MaxAgeSeconds>3000</MaxAgeSeconds>
        <AllowedHeader>*</AllowedHeader>
    </CORSRule>
</CORSConfiguration>
```

Thank you and appreciate your time. -Chris

**Comment by gsuess** [comment]
It is AWS S3 that needs to send the correct CORS headers and NOT your meteor server. So unless you need it for something else, remove that server side `WebApp.connectHandlers` thing.

Now clearly you are not getting the correct CORS headers from the destination that you are uploading to.

This can only mean two things:

 1. You have not setup CORS correctly or
 2. `documents-cleaved` is not the correct bucket...

And I think it's 2. because in your policy you named it `cleavedfiles`.

**Comment by centinel3** [comment]
Hey gsuess,

Thanks for getting back with me. I ended up fixing the issue and believe you are correct. I ended up removing the bucket policy (as I don't believe it's necessary with slingshot), as well as removing the WebApp.connectionHandlers piece as well.

With CORS, I read in Stackoverflow that in some instances, if you use: 
<AllowedOrigin>*</AllowedOrigin> 
instead of:
<AllowedOrigin>http://*</AllowedOrigin> 
it won't add the AllowedOrigin header. I'm not sure if you have run into this, or if there is any downside to adding http://* and https://* as separate entries as I have above.

Thank you again for your response and hope you are doing well. -Chris

**Comment by rashmimhatre100** [comment]
Somebody tried to answer But I am not getting it. You try your luck. https://codexample.org/questions/9358/no-access-control-allow-origin-error-in-meteor-app.c

**Comment by chrischenyc** [comment]
My case was because I didn't use default S3 region, and I didn't include `AWSRegion` in the root level of settings-development.json file

It's actually documented (buried) in the README.md

> Note: If your bucket is created in any region other than US Standard, you will need to set the region key in the directive. Refer the AWS Slingshot Storage Directives
