### ISSUE TITLE
Is there a possibility to save just the key to the DB?

### ISSUE THREAD

**Issue by kevman** [CulturalMe/meteor-slingshot#11]
How can I save just the key without the scheme, bucket name and S3 domain name?

**Comment by ibussieres** [comment]
For some reason I can't get it to work. uploader.instructions is undefined and uploader.param('key') is not returning anything either.  What am I missing ?

    var uploads = _.map(files, function (file) {
        var uploader = new Slingshot.Upload("uploads");
        uploader.send(file, function (error, downloadUrl) {
          if (error) {
            throw new Meteor.Error(500, error.message);
          }

          var doc = {
            size: file.size,
            url: downloadUrl,
            key: // ??
            type: event.target.fileType.value
          };
        });

        return uploader;
      });
