### ISSUE TITLE
TypeError: Object has no method 'fileRestrictions'

### ISSUE THREAD

**Issue by devlesedi** [CulturalMe/meteor-slingshot#121]
I have wasted hours trying to get this package running and getting this error. I have a custom package which is using slingshot. Is there a particular order I must load my files? 
Here is how I'm calling my api.addFiles:

server - Slingshot.createDirective("s3-uploads", {...});
server/client - Slingshot.fileRestrictions("s3-uploads", {...});
client - new Slingshot.Upload("s3-uploads");

Edit: I console logged Slingshot on the server side and the method fileRestrictions is *not* there. Not sure if the docs are old or the API has been changed. Managed to have it working without declaring fileRestrictions.

**Comment by gsuess** [comment]
`fileRestrictions()` must come before the `createDirective()` and it is on the server. What version of slingshot are you using?

**Comment by devlesedi** [comment]
Not sure what version. I only started using it yesterday through ```meteor add edgee:slingshot```
I tried loading ```fileRestrictions()``` first but I get same error. Maybe I was doing something wrong. I also noticed ```createDirective()``` accepts ```maxSize``` and ```allowedFileTypes``` settings.

**Comment by gsuess** [comment]
Yes, `createDirective()` accepts those too. But the advantage of using `fileRestricitons()` is that it makes the client aware of the restrictions and as such can provide client side validations before the upload starts.

**Comment by derwaldgeist** [comment]
I've got the same problem.
Slingshot.fileRestrictions() is definitely called before Slingshot.createDirective(), but still an exception is thrown:

``` js
TypeError: Object [object Object] has no method 'fileRestrictions'
at Slingshot.createDirective.bucket
```

**Comment by chrise86** [comment]
Also getting this issue. Bit of confusion, where exactly should the file restrictions live? @gsuess comments above suggest it is on the server:

> fileRestrictions() must come before the createDirective() and it is on the server. What version of slingshot are you using?

However I get `TypeError: Object [object Object] has no method 'fileRestrictions'`

**Comment by x5engine** [comment]
This is still a big issue!! is there any fix or at least a workaround?

**Comment by charliegn** [comment]
Please advise what to do here.  I have `.fileRestrictions()` just before the `.createDirective()` so why it says there's no method is beyond me.

**`/packages/my-uploader/server/slingshot.config.js`**

```
Slingshot.fileRestrictions( "uploadToAmazonS3", {
  allowedFileTypes: [ "image/png", "image/jpeg", "image/gif" ],
  maxSize: 10 * 1024 * 1024
});


Slingshot.createDirective( "uploadToAmazonS3", Slingshot.S3Storage, {
  bucket: "<myBucketName>",
  acl: "public-read",
  // allowedFileTypes: [ "image/png", "image/jpeg", "image/gif" ], 
  // maxSize: 1 * 1024 * 1024,
  authorize: function () {

    if (!this.userId) {
      var message = "Please login before uploading files";
      throw new Meteor.error("Login Required", message);
    }

    return true;

  },
  key: function ( file ) {
    return "images/" + file.name;
  }
});
```

When I put the `Slingshot.fileRestrictons()` in the `both` directory of my package I don't get any `.fileRestrictions()` errors anymore, but then I do get an error within the `.createDirective()` method saying it can't find `maxSize` so I'm thinking at that point the `Slingshot.fileRestrictions()` may not of loaded anyway?  

I can hard code the `maxSize` & `alllowedFileTypes` (as you can see I've commented out) in the `.createDirective()` and my app stops throwing errors, but it seems as though the above code should work.

Please help.

**Comment by cunneen** [comment]
Try forcing an update of the version:

```
meteor update edgee:slingshot
```
