### ISSUE TITLE
Question - Is there any tracking of which user uploaded a specific file?

### ISSUE THREAD

**Issue by jimmiebtlr** [CulturalMe/meteor-slingshot#126]
I see the metadata portion for the upload authorization, but as far as I can tell there isn't a way to determine that a user did indeed upload a specific file.

What I'm trying to do is secured, authenticated downloads, using slingshot to handle the upload portion.

A brief attempt at a specific example of when it would be useful.

Given we have an object, and that object has an associated file, how can we tell that the file does indeed belong to the object?  
Given user A uploads a file, then inserts an object associated with it. How can we be sure user B cannot upload an object with the same url and have some amount of ownership over it.

I'm not sure if my example is at all clear.

**Comment by gsuess** [comment]
Simple: Do not authorize user B to upload the file to the same path.

**Comment by jimmiebtlr** [comment]
Wow, I was way over thinking it.  Thanks.
