### ISSUE TITLE
Package installs as version 0.0.3 as default

### ISSUE THREAD

**Issue by derwaldgeist** [CulturalMe/meteor-slingshot#131]
After some heavy debugging (I did not get a Blob upload working), I've noticed that the edgee:slingshot package is installed as version 0.0.3 if you add it to Meteor. I did not see this, because I was using the package inside an own package. When I was wondering why the code in my debugger was different form the Github repository, I added the package using meteor add, and this is where I saw that the version was on 0.0.3 and Meteor offered an update. Is there any reason why this package does not install itself as the latest version?

**Comment by gsuess** [comment]
I have noticed this behaviour with other packages too. So think this is a general Meteor problem, but haven't researched this issue further.

**Comment by derwaldgeist** [comment]
Thanks for your quick reply. Yes, I also wondered if this may be a generic Meteor problem - and if you've noticed this with other packages, it surely is. Bad thing is, that this behaviour might cost you hours of debugging, just because the documentation does not seem to match the code :-)

**Comment by derwaldgeist** [comment]
Reported this behaviour as an issue to the main Meteor repo now:
https://github.com/meteor/meteor/issues/5101
