### ISSUE TITLE
Writing to collection in the uploader.send callback

### ISSUE THREAD

**Issue by aadamsx** [CulturalMe/meteor-slingshot#139]
I just started using this package, I'm using the following to send files to S3:

uploader.send(file, metaContext, function(error, downloadUrl) { ... });  

In the callback of the uploader.send, I want to write out to a collection the following: fileName, fileType, fileSize, userId, etc.  like this:

```
uploader.send(file, metaContext, function(error, downloadUrl) {
    if (error) {
        // Log service detailed response.
        console.error('Error uploading', uploader.xhr.response);
        alert (error);
     }
    else {
      Meteor.call('insertDownloadUrl', userId, downloadUrl, fileName, fileType, fileSize,  function(error, result){
        if(error) console.log('error', error);
      });
    }
});
```
How can I get this data into the callback of the uploader.send if I can only get the downloadUrl in the callback?

**Comment by aadamsx** [comment]
Figured out the 'uploader' object has everything I need.  Thanks for the great package!

**Comment by patrickml** [comment]
@aadamsx thx for the update it helped me out
