### ISSUE TITLE
Error: socket hang up

### ISSUE THREAD

**Issue by hazio** [CulturalMe/meteor-slingshot#142]
Today I faced a new type of error while trying to upload a picture to S3 using slingshot. I'm not sure if this error is slingshot fault, but maybe you could help me tracking this bug.

The error message:
W20151004-07:37:09.069(3)? (STDERR) stream.js:94
W20151004-07:37:09.069(3)? (STDERR)       throw er; // Unhandled stream error in pipe.
W20151004-07:37:09.069(3)? (STDERR)             ^
W20151004-07:37:09.069(3)? (STDERR) Error: socket hang up
W20151004-07:37:09.070(3)? (STDERR)     at SecurePair.error (tls.js:1011:23)
W20151004-07:37:09.070(3)? (STDERR)     at EncryptedStream.CryptoStream._done (tls.js:703:22)
W20151004-07:37:09.070(3)? (STDERR)     at CleartextStream.read [as _read] (tls.js:499:24)
W20151004-07:37:09.070(3)? (STDERR)     at CleartextStream.Readable.read (_stream_readable.js:341:10)
W20151004-07:37:09.070(3)? (STDERR)     at EncryptedStream.onCryptoStreamFinish (tls.js:304:47)
W20151004-07:37:09.070(3)? (STDERR)     at EncryptedStream.g (events.js:180:16)
W20151004-07:37:09.070(3)? (STDERR)     at EncryptedStream.emit (events.js:117:20)
W20151004-07:37:09.071(3)? (STDERR)     at finishMaybe (_stream_writable.js:360:12)
W20151004-07:37:09.071(3)? (STDERR)     at endWritable (_stream_writable.js:367:3)
W20151004-07:37:09.071(3)? (STDERR)     at EncryptedStream.Writable.end (_stream_writable.js:345:5)
W20151004-07:37:09.071(3)? (STDERR)     at EncryptedStream.CryptoStream.end (tls.js:641:31)
W20151004-07:37:09.071(3)? (STDERR)     at Socket.onend (_stream_readable.js:502:10)
W20151004-07:37:09.071(3)? (STDERR)     at Socket.g (events.js:180:16)
W20151004-07:37:09.071(3)? (STDERR)     at Socket.emit (events.js:117:20)
W20151004-07:37:09.071(3)? (STDERR)     at _stream_readable.js:944:16
W20151004-07:37:09.072(3)? (STDERR)     at process._tickDomainCallback (node.js:492:13)

**Comment by gsuess** [comment]
This does not look to be related to slingshot at all. The stack doesn't contain any reference to it or anything it may be using. What makes you think otherwise?

**Comment by hazio** [comment]
My meteor app produces that error when using slingshot. I guess it's a coincidence. You can close this issue. Thanks.
