### ISSUE TITLE
restrict specific file types?

### ISSUE THREAD

**Issue by JuanCrg90** [CulturalMe/meteor-slingshot#145]
Hi, i need restrict the upload of music and video files (mp3, wma, wav, mov, mpg, etc).

Exist the way for only block these file types and allow all others?

**Comment by gsuess** [comment]
You could implement this in your authorize function.

**Comment by JuanCrg90** [comment]
Hi, i restricted the files using a regex.

`allowedFileTypes: /^(?!.*(video|audio))/`

Thanks.

**Comment by trakkif** [comment]
JuanCrg90 unfortunately your suggested regex doesn't work - using it I can still upload a jpeg file using the control.

**Comment by trakkif** [comment]
(but this one did:)

allowedFileTypes: /^video\/.*$/

**Comment by mroftalp** [comment]
Is there a way to allow all file types?

**Comment by JuanCrg90** [comment]
Thank you for the tip @trakkif.


@mroftalp  you can personalize this in 


```
Slingshot.fileRestrictions("myFileUploads", {
  allowedFileTypes: ["image/png", "image/jpeg", "image/gif"],
  maxSize: 10 * 1024 * 1024 // 10 MB (use null for unlimited).
});
```

`allowedFileTypes RegExp, String or Array (optional) - Allowed MIME types. Use null for any file type.`

I going to close this thread.
