### ISSUE TITLE
File Download From S3

### ISSUE THREAD

**Issue by dominicarrojado** [CulturalMe/meteor-slingshot#149]
I know the description of this package only says uploading. But I'm just curious on how can I implement downloading. Maybe you can suggest to me something. I would really appreciate it. Thank you! :)

**Comment by boustanihani** [comment]
you can use https://www.npmjs.com/package/download combined with https://github.com/meteorhacks/npm for downloading files...

**Comment by dominicarrojado** [comment]
@boustanihani how do you do this? Can you show me how. Thanks!!!

**Comment by boustanihani** [comment]
First do ```meteor add meteorhacks:npm```

Then create a file called ```packages.json``` and put this inside:
```json
{
    "download": "4.4.1"
}
```

Finally try this sample code:
```javascript
if (Meteor.isServer) {

    var Download = Meteor.npmRequire('download');

    new Download({
            mode: '666'
        })
        .get('https://github.com/kevva/download/archive/master.zip')
        .dest('/absolutePathToYourDownloadFolder...')
        .run();
}
```

Note: **You will need to start your server again after npm has been initialized.**

**Comment by dominicarrojado** [comment]
@boustanihani Yea that's what I did, if I'm calling this in server as a method what should I return in the client?

**Comment by boustanihani** [comment]
I don't know what you are trying to do?? The code above is for downloading a file on the server side. To let a client download the file simply open the url in a new tab:

```window.open("https://github.com/kevva/download/archive/master.zip", "_blank");```

**Note: PopUps should be enabled for this to work!**

**Comment by dominicarrojado** [comment]
Oh yea I've managed to do it a while ago. @boustanihani Haha it was as simple as that. Haha. Just a random question if you know how to change the file name of the captured file in <input type="file"/> cause I don't want spaces its breaking the link.

**Comment by boustanihani** [comment]
What do you mean by the "captured file"? Usually S3 will replaces spaces by a "+" character...

**Comment by dominicarrojado** [comment]
I mean the file on the input type="file". S3 has no problem but saving the link in database does not replace spaces by a "+" character. Which if I get the link from database and put in on a link tag <a></a> the link will have spaces

**Comment by dominicarrojado** [comment]
I have to close this. Already resolve on my own. Hehe. Thanks!

**Comment by rpesciotta** [comment]
Hi @dominicarrojado, would you mind sharing your solution?
I'm going through something similar.. Now that my files are on S3, I need a safe way to retrieve them - thus the idea of having the same mechanism used for upload, but now for download. Did you achieve this?

**Comment by dominicarrojado** [comment]
@rpesciotta Hi. For the download, I just use the url given after the upload.
`<a href="s3_url" download></a>`

And in your S3 amazon check the permissions of the file, it should only let the users read the file so it would be safe. And I also made the file key of S3 (fileId) random to add more security check below. This is from the createDirective of slingshot. 

```
key: function (file, metaContext) {
        var user = Meteor.users.findOne(this.userId);
        return metaContext.folderName + "/" + metaContext.fileId;
    }
```

**Comment by jamauro** [comment]
> For the download, I just use the url given after the upload.
`<a href="s3_url" download></a>`

When I use this, it sends the user to a new page with the S3 url. Is it possible to have the file download directly to the user's computer instead?


> And in your S3 amazon check the permissions of the file, it should only let the users read the file so it would be safe

What's the best way to accomplish this?
