### ISSUE TITLE
Cannot upload the same file

### ISSUE THREAD

**Issue by mroftalp** [CulturalMe/meteor-slingshot#156]
Is it by default that I can't upload the same file again? There's no error showing. Its just not doing anything but choosing a different file will make it work again.

**Comment by ko0stik** [comment]
The reason you don't see any error is because you just replaced your file with the new upload. Take a look at the time it's been uploaded or try uploading two different files with the same name. The first should be overwritten by the second.

**Comment by mroftalp** [comment]
Got it Thanks! @ko0stik

**Comment by sarita-dc** [comment]
What if i want to show error saying "You are uploading same image" or allow them to upload same image.
