### ISSUE TITLE
Allowed file types rejected randomly 

### ISSUE THREAD

**Issue by calvin-evans** [CulturalMe/meteor-slingshot#163]
About 25% of the time I'm getting an error saying the file type <insert mime type> isn't allowed. I've tried really relaxed regexes, specifically allowing that file type in an array of strings etc. Think it's safe to say it's not my `allowedFileTypes` configuration. 

Is this a bug?

**Comment by carlevans719** [comment]
I was having this issue too -- turns out it was the regex failing because of the 'g' flag. 
See [this](http://stackoverflow.com/questions/1520800/why-regexp-with-global-flag-in-javascript-give-wrong-results) SO answer about it.

Removing the 'g' from my `allowedFileTypes` regex fixed the problem.
