### ISSUE TITLE
Meteor 1.3 error

### ISSUE THREAD

**Issue by Lenin7** [CulturalMe/meteor-slingshot#166]
Error when trying to upload a file with meteor 1.3:
//client
{error: 400, reason: "Match failed", details: undefined, message: "Match failed [400]", errorType: "Meteor.Error"}

//server
Exception while invoking method 'slingshot/uploadRequest' Error: Match error: Failed Match.OneOf or Match.Optional validation

//more info
code works fine on Meteor 1.2

**Comment by Lenin7** [comment]
https://github.com/meteor/meteor/issues/5712

**Comment by digz6666** [comment]
Have you resolved the issue? I'm on meteor 1.2 and it throws same error.

**Comment by izaa** [comment]
I had same error when sending only string to Slingshot.Upload("directiveName", param) <-- here param should be object not a string.
