### ISSUE TITLE
Is this package still actively maintained?

### ISSUE THREAD

**Issue by zayaisshawn** [CulturalMe/meteor-slingshot#168]

**Comment by jshimko** [comment]
Looks like these guys are gone.  Edgee.com appears to be dead and none of the repos in this account have seen any attention since last year.  Bummer.  :(

**Comment by zayaisshawn** [comment]
Bummer. I can't decide which one to use for production meteor-slingshot or cfs gridfs and use compose.io to host my database. Technically retrieving files would be faster from gridfs right? Btw I like your geocomplete package. :)

**Comment by jshimko** [comment]
For what it's worth, this package still works fine.  I use it regularly. 

As for GridFS, I'm sure it would work fine for you, but I can't see many advantages to using that over S3 (or similar) - especially if you're going to pay for your Mongo hosting with a provider like Compose.io.  Compose [charges by the storage space](https://compose.io/pricing/).  If you're storing large binary files, it won't take very long to exceed your quotas and start spending big $.  Considering [the cost of S3](https://aws.amazon.com/s3/pricing/), it seems like a no-brainer if you're dealing with volume or want to use a CDN like [Cloudfront](https://aws.amazon.com/cloudfront/). 

Also, I'm not sure why GridFS would be faster than S3/Cloudfront at retrieving files.  I haven't done any serious testing of that theory, but I'm pretty sure that's fairly unlikely considering the primary feature of Cloudfront is fast/efficient file retrieval.

**Comment by zayaisshawn** [comment]
I see, thanks for clarification. I also find [this](https://themeteorchef.com/blog/managing-static-content/) article very helpful.
