### ISSUE TITLE
how to upload file from URL to S3?

### ISSUE THREAD

**Issue by tahaykNSM** [CulturalMe/meteor-slingshot#184]
Hello
I used meteor slingshot too many times and it is pretty amazing,
But now I'm trying to upload a file (image) from other URL,
is there any way to do something like this:
`uploader.send(URL, callback)` ??

**Comment by tahaykNSM** [comment]
I solved it using [meteorhacks:npm](https://github.com/meteorhacks/npm) and [knox](https://www.npmjs.com/package/knox#put)

```
var knox = Meteor.npmRequire("knox");
var client = knox.createClient({
    bucket: Meteor.settings.private.Bucket,
    key: Meteor.settings.private.AWSAccessKeyId,
    secret: Meteor.settings.private.AWSSecretAccessKey,
    region: Meteor.settings.private.AWSRegion
});
http.get(URL, function(res){
  var headers = {
      'Content-Length': res.headers['content-length']
    , 'Content-Type': res.headers['content-type']
  };
  var req=client.putStream(res, '/FILE_NAME.EXT', headers, function(err, res){
    // check `err`, then do `res.pipe(..)` or `res.resume()` or whatever. 
  });
 req.on('response', function (res) {
        if (200 == res.statusCode) {
            console.log('saved to %s', req.url);
            promes.return(req.url);
        }
    });
});
```

**Comment by evolross** [comment]
FYI, this can also be solved using `XMLHttpRequest` and downloading the image to the client browser first, then uploading the normal way with Slingshot. Check this Meteor[ forum post](https://forums.meteor.com/t/download-with-meteor-http-upload-to-s3/24608/5) for more info.
