### ISSUE TITLE
Error: Match error: Expected plain object

### ISSUE THREAD

**Issue by jamgold** [CulturalMe/meteor-slingshot#2]
When I get to this part in my example

```
uploader.send(document.getElementById('input').files[0], function (error, url) {
  Meteor.users.update(Meteor.userId(), {$push: {"profile.files": url}});
});
```

it always fails with error in view.js:406

```
Error: Match error: Expected plain object
```

**Comment by jessedvrs** [comment]
Try this in Safari: `check($0, Element);`
`$0` equals the element you select in the elements panel
The error shows up again *Match error: Expected plain object*
But when I try `$0 instanceof Element` the console will output `true`.
