### ISSUE TITLE
App crashes when i use it with Cordova

### ISSUE THREAD

**Issue by factualz** [CulturalMe/meteor-slingshot#24]
Great package. Works fine in web. However, when i use with Cordova, it causes the app to crash. Any fixes i can apply?

**Comment by MichaelFBA** [comment]
Just FYI its working with Cordova for me.

**Comment by gsuess** [comment]
Yea it seems to be working fine. Thank you.

**Comment by geritol** [comment]
could you post some example code or meteor app?
I cant get this to work.
Thanks a lot!
