### ISSUE TITLE
Forbidden 403 when using this.uploader.url(true)

### ISSUE THREAD

**Issue by radiegtya** [CulturalMe/meteor-slingshot#26]
When I was using this code from example

```
<template name="myPicture">
  <img src={{url}}/>
</template>
Template.myPicture.helpers({
  url: function () {
    //pass true to download the image into cache (preload) before using it.
    return this.uploader.url(true);
  }
});
```

I am getting error message: 
 GET https://piyiku.s3.amazonaws.com/brendan-rodgers-soccer-friendly-manchester-city-vs-liverpool-fc-850x560.jpg/ 403 (Forbidden)

The image actually have been uploaded correctly, but I can't display the image using above helpers example.

Any suggestion about this?

Thanks

**Comment by frco9** [comment]
There's a typo in the doc : 

```
 <img src={{url}}/>
```

Should be 

```
 <img src="{{url}}" />
```
