### ISSUE TITLE
S3 region issue

### ISSUE THREAD

**Issue by awijnen** [CulturalMe/meteor-slingshot#33]
First off, awesome work on this plugin.

I did find an issue with getting slingshot to work with an S3 bucket that's not initialized to the default region (i.e. 'US Standard').

To make sure it was just a region issue, I tried following along with the simple example in the README an posting to 3 different S3 buckets, which are all under the same account, and have gotten the same CORS configuration.

First I added the directive server-side, added the AWS key and secret to Meteor.settings, and configured the S3 buckets. Then I used the uploader from the client using the console:
```JavaScript
var t = document.getElementById('test').files[0]
```
```
File {webkitRelativePath: "", lastModified: 1393941506000, lastModifiedDate: Tue Mar 04 2014 14:58:26 GMT+0100 (CET), name: "bicycle_road.jpeg", type: "image/jpeg"…}
```

```JavaScript
var uploader = new Slingshot.Upload("myFileUploads");
```
```
Slingshot.Upload {status: function, progress: function, uploaded: function, send: function, request: function…}
```
```JavaScript
uploader.send(t, function(err, downloadUrl) {
if (err) {console.dir(err);} else {console.dir(downloadUrl);}
});
```

Here are the issues I ran into following along with the example in the README:
1) S3 bucket region: Frankfurt
    console error log: 

```
POST https://fotoposterdev.s3.amazonaws.com/ 400 (Bad Request)
VM3007:3 Meteor.makeErrorType.errorClassdetails: undefinederror: "Bad Request - 400"errorType: "Meteor.Error"message: "Failed to upload file to cloud storage [Bad Request - 400]"reason: "Failed to upload file to cloud storage"stack: (...)get stack: function () { [native code] }set stack: function () { [native code] }__proto__: _.extend._inherits.Middle 
```

2) S3 bucket region: Oregon
    console error log:

```
 XMLHttpRequest cannot load https://fpawdev.s3.amazonaws.com/. The request was redirected to 'https://fpawdev.s3-us-west-2.amazonaws.com/', which is disallowed for cross-origin requests that require preflight.
VM3265:3 Meteor.makeErrorType.errorClassdetails: undefinederror: " - 0"errorType: "Meteor.Error"message: "Failed to upload file to cloud storage [ - 0]"reason: "Failed to upload file to cloud storage"stack: (...)get stack: function () { [native code] }set stack: function () { [native code] }__proto__: _.extend._inherits.Middle
```

3) S3 bucket region: US Standard ==> SUCCESS
    console log:
```
Slingshot.Upload {status: function, progress: function, uploaded: function, send: function, request: function…}
VM3534:3 https://fptestdev.s3.amazonaws.com/undefined/bicycle_road.jpeg
```

**Comment by gsuess** [comment]
The reason why Frankfurt doesn't work is because slingshot uses AWS Signature Version 2.

> Any new regions after January 30, 2014 will support only Signature Version 4 and therefore all requests to those regions must be made with Signature Version 4.

So it needs an upgrade for the signing method.

I have totally missed the existence of the new signing method in the docs before.
