### ISSUE TITLE
Possible to upload from url?

### ISSUE THREAD

**Issue by voidale** [CulturalMe/meteor-slingshot#36]
Hello,
I must say this is really nice concept lightweight on resources I want to use this package it's amazing. But I also have another use of uploading images from URL server side, so I was wondering if it's also possible to upload images from url's and receive back the amazon s3 url?

**Comment by gsuess** [comment]
@voidale if I am not mistaken, Cloudinary allows it: 

> file - Either the actual data of the image or an HTTP URL of a public image on the Internet.

http://cloudinary.com/documentation/upload_images
