### ISSUE TITLE
Support for Audio (.mp3, .ogg) File Types

### ISSUE THREAD

**Issue by etmarch** [CulturalMe/meteor-slingshot#41]
From the readme file: "This directive will not allow any files other than images to be uploaded. The policy is directed by the meteor app server and enforced by AWS S3."

I am primarily concerned with uploading Audio files at the moment, is this even a possibility with this package or should I look into other options?

**Comment by gsuess** [comment]
The readme refers to the directive given in the example, which is set to be restricted to images only. You can change that to be for audio only. Or be more permissive and allow any content type. It is up to you.

Allow you need to do is set `allowedFileTypes` to mime type that you want in the directive. 

Even latency compensation should work, however you would have to make sure that playback is not interrupted once the file finished uploading.

**Comment by etmarch** [comment]
Oh what wonderful news! Looks like this will be a great solution for my audio upload/playback functionality requirements, as it seems much more efficient than saving the files to the local server. 

One more question - do you have any advice how I would go about creating a "location/directory" for each registered user to upload their files to? This question may be beyond the scope of this package, and if so I apologize. Thanks for the great package though!

**Comment by gsuess** [comment]
both google cloud and aws s3 will create the directories automatically for you. Just set the key properly with directory prefix.

**Comment by etmarch** [comment]
Excellent, thanks again for your help!
