### ISSUE TITLE
Allow for uploads with no userId

### ISSUE THREAD

**Issue by cavill** [CulturalMe/meteor-slingshot#42]
Currently it seems you have to be a signed-in user to create an upload:

    var context = {
        userId: Meteor.userId()
    };

(line 70, upload.js)

Is there a way we can avoid that restriction? I can think of a few scenarios where it wouldn't be necessary.

**Comment by gsuess** [comment]
No. It is not required to have signed-in user. That line just reads the current user to be passed on to the authentication functions among other for further processing.

If you want to allow anonymous uploads, then return true on `authorize()` even when `this.userId` is falsy.

**Comment by cavill** [comment]
Great, thanks.
