### ISSUE TITLE
Delete files off S3 

### ISSUE THREAD

**Issue by centinel3** [CulturalMe/meteor-slingshot#50]
Feature request:

Are there any plans to allow the user to delete/remove files off amazon S3 storage? 

Thanks and will talk with you soon. -Chris

**Comment by gsuess** [comment]
Hey, this is currently not within the scope of the package. I would recommend using knox or similar to send delete request from the meteor server (not the client browser).

**Comment by centinel3** [comment]
Ok. Thanks! 

With this package do you have access to Knox server side?

**Comment by gsuess** [comment]
No, but there are plenty of packages available for knox. It doens't have to be knox either there is also aws-sdk.

The reason Slingshot doesn't provide any of that, is because it is supposed to be lightweight.

Organizing and deleting files from the bucket is not something that should be handled by slingshot directives.

**Comment by centinel3** [comment]
Thanks again. Love the package! Talk with you later. -Chris

**Comment by vertangelx** [comment]
I need this feature as well. Any recommendations for a Meteor package that is lightweight enough for use with the sole purpose of deleting files?

**Comment by gsuess** [comment]
You can try this:

```JavaScript
Meteor.methods({
  deleteFile: function (key) {
    //TODO Check if authorization etc...

   HTTP.call("DELETE", Slingshot.S3Storage.bucketUrl("mybucket", region) + "/" + key, {
     headers: {
        authorization: Slingshot.S3Storage.signAwsV4(canonicalRequest, AWSSecretAccessKey, date, region, "s3")
     }
   });
  });
});
```

So you need `region`, `canonincalRequest` (see docs below), `AWSSecretAccessKey` and the `date` (yyyymmdd).

I believe future future versions of slingshot will have a canonicalRequest method that you can use as it will be needed for #5. 

http://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-query-string-auth.html

**Comment by meteorjs3000** [comment]
@gsuess How do you get `canonicalRequest` and `date`? Do you store `date` in Mongodb when the file was initially uploaded to S3 so you can retrieve it now when deleting that file?

**Comment by centinel3** [comment]
@gsuess 
Thank you again for the nudge in the right direction. Much appreciated! 

For anyone looking to delete off Amazon S3, see my code snippet below.
(be sure to download and install an Amazon SDK package from Meteor Atmosphere)

(On a server method):

AWS.config.update({
   accessKeyId: Meteor.settings.private.amazonS3.AWSAccessKeyId,
   secretAccessKey: Meteor.settings.private.amazonS3.AWSSecretAccessKey
});

var s3 = new AWS.S3();
   var params = {
   Bucket: Meteor.settings.private.amazonS3.bucket,
   Key: data.Key
};

var deleteObject = Meteor.wrapAsync(
   s3.deleteObject(params, function(error, data) {
      if(error) {
         console.log(error);
      } else {
         console.log(data);
      }
   })
);

---
Thanks again,
Chris Campbell
http://cleaved.com

**Comment by filipecoelho** [comment]
Hello @centinel3, what would be the `data.Key`?

**Comment by filipecoelho** [comment]
Hum, now I did!!
Is the name of the file or the real path key created at the time of storage. In my case it `photos / 1342asf1sag3520_42tdgklaat02tmsga.png`

**Comment by centinel3** [comment]
Yes, the key is the path to the blob object. Glad you figured it out!

**Comment by aadamsx** [comment]
Should the blob object be the full path, including the http portion -- like the path we get on the callback to the uploader -> downloadUrl?

**Comment by markoshust** [comment]
Has anyone done this with Google Cloud Storage?

**Comment by Roshdy** [comment]
@centinel3 can you please post a sample call from client?
