### ISSUE TITLE
Progress bar question

### ISSUE THREAD

**Issue by centinel3** [CulturalMe/meteor-slingshot#52]
When using the progress bar I'm running into an issue when I use this as a template. I have copied and pasted in the exact code you have on github. Then I'm including it as a template within my main page `{{progressBar}}`.

I'm getting:
```
Exception in template helper: TypeError: Cannot read property 'progress' of undefined
```

It looks to me that it's not realizing the uploader instance. I've tried moving the upload constructor to the Template.myPage.render function (as well as some other things) and am not able to figure it out. 

Any help would be appreciate with this. Thank you in advance! -Chris

Currently I have the code within my form submit function:

```JavasCRIPT
Template.imagesSubmitTpl.events({
  'submit form': function(e, template) {
    e.preventDefault();
    
    // Saving to Amazon S3
    var metaContext = {
      projectId: this._id
    }

    var uploader = new Slingshot.Upload("imagesCleaved", metaContext);

    uploader.send(document.getElementById('imageUpload-js').files[0], function (error, downloadUrl) {
      // Client-side error handling
      if (error) {
        console.error(error);
      }

      // Saving to the DocumentsCollection in Mongodb (upon successful save to Amazon S3)
      // Stripping out the full file path and saving only the image name itself
      var imageInput = $(e.target).find('#imageUpload-js').val();
      var imageFileName = imageInput.split('\\').pop().split('/').pop();
      
      var images = {
        projectId: template.data._id,
        imageFileName: imageFileName,
        imageName: $(e.target).find('[name=imageName-js]').val(),
        imageUrl: downloadUrl,
        imageNote: $(e.target).find('[name=imageNote-js]').val()
      };

      Meteor.call('imagesInsert', images, function(error, result){
        if (error){
          return alert(error.reason);
        }

        //Clear form
        $('#upload-images-entry-js')[0].reset();
      });
    });
  }
});
```

Progress bar code:
I'm including your code as a template, unmodified at the moment.

**Comment by gsuess** [comment]
I don't see how you could possible access the uploaders progress bars from your template's helpers, since `uploader` only lives in the scope of your submit for event handler.

Checkout this example:


```JavaScript
var uploader = new ReactiveVar();

Template.upload.helpers({

    isUploading: function () {
        return Boolean(uploader.get());
    },

    progress: function () {
        var upload = uploader.get();
        if (upload)
            return Math.round(upload.progress() * 100);
    }
});

Template.upload.events({
    "submit .form": function (event, template) {
        var upload = new Slingshot.Upload("imagesCleaved"),
              file = template.find("#imageUpload-js").files[0];
        if (file) {
            upload.send(file, function (error, url) {
                uploader.set();

                if (error) {
                    alert(error.message);
                }
                else {
                    //TODO Call your method here
                }
            });
        }

        uploader.set(upload);
    }
});

```

**Comment by centinel3** [comment]
That is perfect! Thank you!

I did notice that the NaN is coming through first, before the progress value increments. Is there a way to start at 0 initially, instead of NaN?

Also, you have an isUploading helper, but I don't see it being used. Is there a reason for this, or are you showing me a way to show/hide the progress bar using spacebars and this helper?

-Chris

**Comment by gsuess** [comment]
> Is there a way to start at 0 initially, instead of NaN?

Just append `|| 0` to return value of the progress helper.

> Also, you have an isUploading helper, but I don't see it being used. Is there a reason for this, or are you showing me a way to show/hide the progress bar using spacebars and this helper?

The latter :)

**Comment by centinel3** [comment]
Thanks again! Love the package! Keep up the good work! -Chris
