### ISSUE TITLE
upload to US Standard region failing with 0.4.0

### ISSUE THREAD

**Issue by astraw** [CulturalMe/meteor-slingshot#53]
Hi,

A "meteor update" broke my previously working setup in which I configure slingshot with a --settings CLI argument containing the following (substituting my actual values):

    {"AWSAccessKeyId": "my_key",
     "AWSSecretAccessKey": "my_secret_key",
     "S3Bucket": "my_bucket"}

In the browser JS console, the first error I see is:

    OPTIONS https://my_bucket.s3-us-east-1.amazonaws.com/ net::ERR_NAME_NOT_RESOLVED

This arises in the line `      xhr.send(buildFormData());` in upload.js.

And indeed, the DNS name does not resolve. However, `my_bucket.s3.amazonaws.com` does resolve and, as far as I can tell, this was the name slingshot 0.3.0 would use.

So it seems, at least for my use of slingshot without setting the "region" variable, the code is now broken.

**Comment by gsuess** [comment]
Hmm, yes, totally overlooked that AWS has a discrepancy there:

Region is "us-east-1", but the domain is:

> s3.amazonaws.com (N. Virginia or Pacific Northwest)
s3-external-1.amazonaws.com (N. Virginia only)

As a workaround you can set a bucketUrl to `"https://my_bucket.s3.amazonaws.com"` while still leaving the region at `"us-east-1"`.

I will push a fix soon though.
