### ISSUE TITLE
aborting an upload

### ISSUE THREAD

**Issue by ChenRoth** [CulturalMe/meteor-slingshot#59]
I've read through the Upload object, couldn't see any such functionality.

Is there currently a way to do that? should there be one?

**Comment by gsuess** [comment]
No there is no such feature at the moment. Certainly there should be one, especially once resumable uploads are integrated.

**Comment by gsuess** [comment]
With 0.6.1 you now [abort](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest#abort()) with: `upload.xhr.abort();`
