### ISSUE TITLE
404 not found when uploading

### ISSUE THREAD

**Issue by radiegtya** [CulturalMe/meteor-slingshot#61]
here is the error message:

GET blob:http%3A//localhost%3A3003/535c7eb4-a6e4-448c-b5d6-6e33246aa7a9/ 404 (Not Found)

idk whats going on, I can use slingshot on the old version, but with the latest version there is error like this.

Thanks

**Comment by gsuess** [comment]
The blob URL gets automatically destroyed once you have completed the upload. So if you try to use it thereafter, you will get this error.

**Comment by radiegtya** [comment]
Then what should I do?

**Comment by gsuess** [comment]
Use the download URL, the one that points to your bucket.

**Comment by gsuess** [comment]
Anyway, without giving me more details, you are keeping me in the blind and I cannot help you than this. All I know is that you are trying to read a file from a temporary blob URL when no longer exists. This will happen when you use `uploader.url()` before your file has uloaded and then keep this value for longer than the upload takes.

A big mistake for example is this code:

```JavaScript
//THIS IS AN EXAMPLE OF WHAT YOU SHOULD NOT DO
var upload  = new Slinghot.Upload("mydir");

upload.send(file);
 MyCollection.insert({url: upload.url()}); //THIS IS BAD
```

`upload.url()` should be used for displaying the files only. And it should be done within reactive computations.
