### ISSUE TITLE
How do you upload a blob?

### ISSUE THREAD

**Issue by Lenin7** [CulturalMe/meteor-slingshot#62]
var blob = createdblob;

uploader.send(blob, function (error, downloadUrl) {
  Meteor.users.update(Meteor.userId(), {$push: {"profile.files": downloadUrl}});
});

Console error: Not a file

**Comment by gsuess** [comment]
If you are using Slinglshot v0.3 or later, `createdblob` must be either a `Blob` or a `File`. If you are using Slingshot prior to v0.3 then it must be a File (blobs were not supported).
