### ISSUE TITLE
Validate function: TypeError

### ISSUE THREAD

**Issue by kevman** [CulturalMe/meteor-slingshot#65]
I'm using Slingshot 0.4.1 and I'm getting the following error:

```javascript
// lib/uploads.js
validate: function(file) {
  var context = {
    userId: Meteor.userId() // Uncaught TypeError: undefined is not a function
  };
  try {
    var validators = Slingshot.Validators,
        restrictions = Slingshot.getRestrictions(directive);

    validators.checkAll(context, file, metaData, restrictions) && null;
  } catch(error) {
    return error;
  }
}
```

**Comment by kevman** [comment]
Update: I need to add at least one login provider package: accounts-password, ...

**Comment by gsuess** [comment]
That is not error, that is just a chunk of source code. What is your error?

**Comment by kevman** [comment]
Without the accounts package you will get the error.

var context = {
    userId: Meteor.userId() // Uncaught TypeError: undefined is not a function
  };

**Comment by kevman** [comment]
Your package depends on accounts too.

**Comment by gsuess** [comment]
Ah sorry, didn't see the comment.
