### ISSUE TITLE
Custom abort event listener

### ISSUE THREAD

**Issue by kevman** [CulturalMe/meteor-slingshot#66]
Is there a way to add a custom abort event listener?

**Comment by gsuess** [comment]
No, currently there is not. But when the transfer is aborted the callback will be called with an error.

Eventually there will be a major overhaul of the client side uploader in which that feature will be added.

**Comment by kevman** [comment]
And a way to add a callback or a hook to the existing abort event listener?
Or using the reactive "status" var?

It would be nice to execute a function after error or abort.

**Comment by gsuess** [comment]
Yes you can do that. Just check for `uploader.status() === 'aborted'` in a reactive computation.
