### ISSUE TITLE
400 (bad request)

### ISSUE THREAD

**Issue by hafiz88** [CulturalMe/meteor-slingshot#67]
Hi, I got this error but the weird thing is I run the same code on multiple pc but only one of them got this error.
![400 bad request](https://cloud.githubusercontent.com/assets/11023148/6206599/c19a1b74-b5c8-11e4-8041-be3e88b37bf8.png)

**Comment by gsuess** [comment]
What is the response you get from that POST?

**Comment by hafiz88** [comment]
I just realize I set the wrong region on aws. Thanks
