### ISSUE TITLE
Upload performance

### ISSUE THREAD

**Issue by micahalcorn** [CulturalMe/meteor-slingshot#68]
Thanks for this great package and thorough Readme with examples.

I am handling some PDF uploads that are 0x.x MB in size and they are taking several minutes to complete. This is much, much slower than my connection speed would imply.

Is there something I need to do on my size or AWS to improve this?

**Comment by gsuess** [comment]
I don't really know why it's running slow for you.

I would recommend trying to isolate it from anything else that may slow it down.

It should not take several minutes to upload small files, however when uploading small files the overhead of establishing the upload will not be negligible. This means that it will take up to twice as long to upload the file than it would be if you just divide the file size by your bandwidth.

**Comment by raza2022** [comment]
@gsuess @micahalcorn have you work around? Hi am getting the same, for 1 MB file it takes 2 and half minutes. i already check my configuration nothing special or extra work. one more thing when i upload the same file directly on aws console it's take less then half minute.
