### ISSUE TITLE
Pass arguments createDirective

### ISSUE THREAD

**Issue by madshargreave** [CulturalMe/meteor-slingshot#71]
Is it possible to pass arguments to the createDirective function, so that one can use such when creating the key/filename?

**Comment by gsuess** [comment]
the createDirective function takes two arguments: `name` and `directiveParams`, in that order. You have to pass pass these two arguments.

**Comment by madshargreave** [comment]
Okay this is what I got

var guid     = guid();
var uploader = new Slingshot.Upload('fileUploads', { guid: guid });

uploader.send(file, function(error, downloadUrl) {
   ...

And then I have my directive

Slingshot.createDirective('fileUploads', Slingshot.S3Storage, {
  bucket: Meteor.settings.S3Bucket,
  region: Meteor.settings.AWSRegion,
  acl:       'public-read',
  ....

But I am not sure how to access the guid I passed in, inside the directive

**Comment by gsuess** [comment]
Your key and authorize functions in the directive will take it as their 2nd argument.

```JavaScript
key: function (fileInfo, metaInfo) {
   console.log(metaInfo.guid);
}
```

**Comment by madshargreave** [comment]
I see, thanks
