### ISSUE TITLE
Request small addition to the docs

### ISSUE THREAD

**Issue by Redroest** [CulturalMe/meteor-slingshot#72]
It costed some time to figure out why  uploader.progress() did'nt update. It turned out that the package: ReactiveVar was not installed..

Can you add some notes to the documentation about this?:

### Add the following package to support reactivity in the progress-bars
meteor add reactive-var

### Preventing NaN errors
if(uploader.uploaded()) {
  console.log(uploader.progress());
}

**Comment by gsuess** [comment]
Hmm, that doesn't make sense. 

It should be installed automatically as it is declared as dependency of slingshot.

What meteor version are / were you using?

**Comment by Redroest** [comment]
Version 1.0.3.1

I'm starting meteor using mrt command. Maybe that makes a difference?

**Comment by gsuess** [comment]
No, meteorite shouldn't affect it.

Can you please try removing ReactiveVar again and see if it will break again?
