### ISSUE TITLE
Return url missing '/' - e.g. 'https:/' instead of 'https://' for 0.6.0

### ISSUE THREAD

**Issue by onegiantleap** [CulturalMe/meteor-slingshot#84]
The url that is returned when a file has been uploaded (using Amazon S3 in my testing) is missing a '/'.

e.g. 'https:/bucket.s3-us-west-2.amazonaws.com' instead of 'https://bucket.s3-us-west-2.amazonaws.com'.

This issues does not occur in version 0.4.0, but it is present in 0.6.0.

Thanks!

**Comment by abhishekbatra** [comment]
The offending line is [this](https://github.com/CulturalMe/meteor-slingshot/blob/master/services/aws-s3.js#L101) path.join joins and then normalizes, resulting in `'//' -> `'/'`

**Comment by abhishekbatra** [comment]
@gsuess Would the following code work as a replacement:

```javascript

downloadPath = (directive.cdn || bucketUrl) + '/' + payload.key;

```

Or is the `path.join` needed for sanitization?

**Comment by abhishekbatra** [comment]
Another shamelessly simple solution seems:

```javascript 
downloadPath = path.join((directive.cdn || bucketUrl), payload.key),
downloadPath.replace('/', '//');
```
