### ISSUE TITLE
How to obtain RackspaceMetaDataKey?

### ISSUE THREAD

**Issue by fardeemmunir** [CulturalMe/meteor-slingshot#87]
I read the documentation but I'm having trouble making it work.

```
POST /v1/MossoCloudFS_0672d7fa-9f85-4a81-a3ab-adb66a880123 HTTP/1.1
Host: storage.clouddrive.com
X-Auth-Token: f064c46a782c444cb4ba4b6434288f7c
X-Account-Meta-Temp-Url-Key: yourKey
```

I was wondering what is the string after `MossoCloudFS`? Also how do I even make this request? Does stuff like [Hurl.it](https://www.hurl.it/) work?

**Comment by gsuess** [comment]
You will need to contact rackspace support if their documentation is not clear enough.
