### ISSUE TITLE
Meteor.settings required for some parameters

### ISSUE THREAD

**Issue by jamgold** [CulturalMe/meteor-slingshot#90]
I notice that Slingshot.createDirective (for S3Storage) allows specifying bucket, AWSAccessKeyId and AWSSecretAccessKey, but not AWSRegion which __must__ be provided in Meteor.settings?

**Comment by gsuess** [comment]
You can specify the region as an argument, but the key would be `region` and not `AWSRegion`:

```JavaScript
Slingshot.createDirective("mydirective", Slingshot.S3Storage, {
  bucket: "mybucket",
  region: "us-west-1", //Overrides Meteor.settings.AWSRegion for this directive.
  ...
});
```
Or you can also set service specific defaults:

```JavaScript
Slingshot.S3Storage.directiveDefault.region = "us-west-1";
```
This does work with any directive that are applicable to the service.

The services defaults override `Meteor.settings` which in turn are overridden by the directive settings.

**Comment by jamgold** [comment]
Damn, totally missed that, thanks a lot.
