### ISSUE TITLE
Is it possible to add support for Dropbox?

### ISSUE THREAD

**Issue by Praxie** [CulturalMe/meteor-slingshot#91]
Hi. I started writing my own Dropbox uploader but I wonder if it's possible to add support for Dropbox to Slingshot, especially resumable upload(chunked) support. 
Cheers!

**Comment by gsuess** [comment]
The slingshot client currently does not support resumable uploads or uploads by parts/chunks. 

Dropbox does not support resumable uploads, but it does support uploads by parts (or chunks). https://www.dropbox.com/developers/core/docs#chunked-upload

Dropbox also does not support signed uploads or single authorized uploads.

What is your use case anyway? Do you want your users to upload files into your account without owning a dropbox account? Dropbox does not seem to support that either.

Slingshot is not made for 3-lagged authentication uploads. So if your use case allowing users to upload files by authorizing it through their own dropbox accounts via oauth, the slingshot is not made for this.

**Comment by Praxie** [comment]
I use dropbox-js lib. So the chunked-upload allows to create resumable upload as each upload step returns a cursor.
http://coffeedoc.info/github/dropbox/dropbox-js/master/classes/Dropbox/Client.html#resumableUploadStep-instance

Use case is to authenticate users first and then allow them to save some files into the App directory within their dropbox accounts.

**Comment by gsuess** [comment]
Yea in my terms, those are not "resumable" uploads as you would need to repeat the upload for the entire chunk if a chunk fails.

Anyway, slingshot is not suitable for your use case as you don't need a directive to manage authentication, because users not uploading to your account, but to their own account.
