### ISSUE TITLE
How to allow arbitrary file extension

### ISSUE THREAD

**Issue by richsilv** [CulturalMe/meteor-slingshot#93]
Apologies if this is very straightforward, but I can't work it out.  How do I allow only files with an extension "abc" for example?

I've tried the following, with no joy:

```
allowedFileTypes: 'abc'
allowedFileTypes: '.abc'
allowedFileTypes: '*.abc'
allowedFileTypes: /^.*\.abc$'
allowedFileTypes: [ 'abc' ]
```
etc.

Thanks very much.

**Comment by gsuess** [comment]
It is not extension based, but mime type based. You can enforce extensions by adjusting your `.key` value.

**Comment by richsilv** [comment]
Thanks for the immediate answer!
